name: stylegaussian
channels:
  - pytorch
  - conda-forge
  - pyg
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pytorch-scatter
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/feature-gaussian-rasterization
    - submodules/simple-knn
    - six
    - tensorboard
    - viser
    - scikit-learn
    - fast_pytorch_kmeans